base_dir: "/scratch/users/jgalante/SparseNet_Snakemake"
latent_base_channels: 64

samples:
  p53:
    peaks_bed: "peaks_inliers.bed"
    negatives_bed: "gc_negatives.bed"
    seqs: "genome.fa"
    signal_plus: "experiment_plus.bw"
    signal_minus: "experiment_minus.bw"
    ctl_plus: "control_plus.bw"
    ctl_minus: "control_minus.bw"
    model_path: "model.h5"

sae_grid:
  expansion_factor: [1.0] # [1.0, 2.0, 4.0, 8.0]
  topk_fraction: [1.0] # [0.05, 0.10, 0.20]
  center_len: [1000]
  # training params (can stay scalar constants)
  epochs: 3
  inner_bs: 16384
  lr: 0.001

pwm_grid:
  num_samples_per_node: [100, 1000, 10000, 100000]
